version: '3'
services:
  postgre:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    ports:
      - "5432:5432"
  webapi:
      build: .
      ports:
        - "5000:80"
volumes:
  db:
    driver: local
  
  